### ISSUE TITLE
New container declaration syntax

### ISSUE THREAD

**Issue by ZeeCoder** [ZeeCoder/container-query#115]
Instead of the very  unconventional `@define-container` syntax, it should be more like a regular declaration, like:

```css
.Container {
  container: true;
}
```
